import type { Category } from '../types';

/**
 * Comprehensive mapping of lowercase app name → category.
 * Used during first-launch to auto-categorize installed applications.
 */
export const APP_CATEGORY_MAP: Record<string, Category> = {

  // ── Development: Editors & IDEs ──────────────────────────────────────────
  'visual studio code':       'Work',   // VS Code
  'cursor':                   'Work',
  'xcode':                    'Work',
  'android studio':           'Work',
  'intellij idea':            'Work',
  'intellij idea ce':         'Work',
  'webstorm':                 'Work',
  'pycharm':                  'Work',
  'pycharm ce':               'Work',
  'goland':                   'Work',
  'clion':                    'Work',
  'datagrip':                 'Work',
  'rider':                    'Work',
  'phpstorm':                 'Work',
  'rubymine':                 'Work',
  'fleet':                    'Work',
  'nova':                     'Work',
  'bbedit':                   'Work',
  'sublime text':             'Work',
  'sublime text 4':           'Work',
  'atom':                     'Work',
  'textmate':                 'Work',
  'espresso':                 'Work',
  'visual studio':            'Work',
  'notepad++':                'Work',
  'brackets':                 'Work',
  'bluefish':                 'Work',
  'geany':                    'Work',

  // ── Development: Terminals ────────────────────────────────────────────────
  'terminal':                 'Work',
  'iterm':                    'Work',
  'iterm2':                   'Work',
  'warp':                     'Work',
  'alacritty':                'Work',
  'kitty':                    'Work',
  'hyper':                    'Work',
  'tabby':                    'Work',
  'cmd':                      'Work',
  'powershell':               'Work',
  'windowsterminal':          'Work',
  'windows terminal':         'Work',

  // ── Development: Database Tools ───────────────────────────────────────────
  'tableplus':                'Work',
  'postico':                  'Work',
  'dbngin':                   'Work',
  'sequel pro':               'Work',
  'mongodb compass':          'Work',
  'dbeaver':                  'Work',
  'redisinsight':             'Work',
  'redis insight':            'Work',
  'studio 3t':                'Work',
  'robo 3t':                  'Work',
  'pgadmin':                  'Work',
  'pgadmin 4':                'Work',

  // ── Development: API & Network ────────────────────────────────────────────
  'postman':                  'Work',
  'insomnia':                 'Work',
  'paw':                      'Work',
  'proxyman':                 'Work',
  'charles':                  'Work',
  'wireshark':                'Work',
  'http toolkit':             'Work',
  'rapidapi':                 'Work',

  // ── Development: Version Control ─────────────────────────────────────────
  'github desktop':           'Work',
  'tower':                    'Work',
  'sourcetree':               'Work',
  'fork':                     'Work',
  'gitkraken':                'Work',
  'sublime merge':            'Work',

  // ── Development: Containers / DevOps ─────────────────────────────────────
  'docker desktop':           'Work',
  'docker':                   'Work',
  'rancher desktop':          'Work',
  'orbstack':                 'Work',

  // ── Development: Simulators / Misc ───────────────────────────────────────
  'simulator':                'Work',
  'instruments':              'Work',
  'loom':                     'Work',
  'obs':                      'Work',
  'obs studio':               'Work',

  // ── Design ────────────────────────────────────────────────────────────────
  'figma':                    'Work',
  'sketch':                   'Work',
  'adobe photoshop':          'Work',
  'adobe illustrator':        'Work',
  'adobe xd':                 'Work',
  'adobe indesign':           'Work',
  'adobe after effects':      'Work',
  'adobe premiere pro':       'Work',
  'adobe lightroom':          'Work',
  'adobe lightroom classic':  'Work',
  'adobe acrobat':            'Work',
  'adobe acrobat reader':     'Utilities',
  'adobe audition':           'Work',
  'adobe animate':            'Work',
  'adobe dimension':          'Work',
  'adobe fresco':             'Work',
  'affinity designer':        'Work',
  'affinity photo':           'Work',
  'affinity publisher':       'Work',
  'canva':                    'Work',
  'principle':                'Work',
  'protopie':                 'Work',
  'origami studio':           'Work',
  'zeplin':                   'Work',
  'framer':                   'Work',
  'pixelmator pro':           'Work',
  'pixelmator':               'Work',
  'screenflow':               'Work',
  'final cut pro':            'Work',
  'davinci resolve':          'Work',
  'logic pro':                'Work',
  'motion':                   'Work',
  'compressor':               'Work',
  'blender':                  'Work',
  'cinema 4d':                'Work',
  'maya':                     'Work',
  'autocad':                  'Work',
  'sketchup':                 'Work',

  // ── Office & Productivity ─────────────────────────────────────────────────
  'microsoft word':           'Work',
  'word':                     'Work',
  'microsoft excel':          'Work',
  'excel':                    'Work',
  'microsoft powerpoint':     'Work',
  'powerpoint':               'Work',
  'microsoft onenote':        'Work',
  'onenote':                  'Work',
  'microsoft outlook':        'Work',
  'outlook':                  'Work',
  'pages':                    'Work',
  'numbers':                  'Work',
  'keynote':                  'Work',
  'libreoffice':              'Work',
  'libreoffice writer':       'Work',
  'libreoffice calc':         'Work',
  'libreoffice impress':      'Work',
  'wps office':               'Work',
  'wps':                      'Work',

  // ── Note-taking & Knowledge ───────────────────────────────────────────────
  'notion':                   'Study',
  'obsidian':                 'Study',
  'logseq':                   'Study',
  'craft':                    'Study',
  'bear':                     'Study',
  'ulysses':                  'Study',
  'day one':                  'Study',
  'drafts':                   'Study',
  'ia writer':                'Study',
  'typora':                   'Study',
  'marktext':                 'Study',
  'notes':                    'Study',
  'joplin':                   'Study',
  'standard notes':           'Study',
  'evernote':                 'Study',
  'devonthink':               'Study',
  'devonthink 3':             'Study',
  'zotero':                   'Study',
  'mendeley':                 'Study',
  'papers':                   'Study',
  'anki':                     'Study',
  'goodlinks':                'Study',
  'reeder':                   'Study',
  'netnewswire':              'Study',
  'readwise reader':          'Study',
  'instapaper':               'Study',
  'pocket':                   'Study',
  'kindle':                   'Study',
  'books':                    'Study',

  // ── Communication ─────────────────────────────────────────────────────────
  'slack':                    'Communication',
  'discord':                  'Communication',
  'zoom':                     'Communication',
  'zoom.us':                  'Communication',
  'microsoft teams':          'Communication',
  'teams':                    'Communication',
  'telegram':                 'Communication',
  'whatsapp':                 'Communication',
  'signal':                   'Communication',
  'viber':                    'Communication',
  'messages':                 'Communication',
  'facetime':                 'Communication',
  'skype':                    'Communication',
  'lark':                     'Communication',
  'feishu':                   'Communication',
  'spark':                    'Communication',
  'mimestream':               'Communication',
  'airmail':                  'Communication',
  'airmail 5':                'Communication',
  'hey':                      'Communication',
  'superhuman':               'Communication',
  'mail':                     'Communication',
  'thunderbird':              'Communication',
  'missive':                  'Communication',
  'caprine':                  'Communication',
  'beeper':                   'Communication',
  'textsoap':                 'Communication',

  // ── Entertainment ─────────────────────────────────────────────────────────
  'spotify':                  'Entertainment',
  'music':                    'Entertainment',
  'podcasts':                 'Entertainment',
  'tv':                       'Entertainment',
  'vlc':                      'Entertainment',
  'iina':                     'Entertainment',
  'infuse':                   'Entertainment',
  'infuse 7':                 'Entertainment',
  'plex':                     'Entertainment',
  'plex media player':        'Entertainment',
  'jellyfin media player':    'Entertainment',
  'emby theater':             'Entertainment',
  'steam':                    'Entertainment',
  'epic games launcher':      'Entertainment',
  'battle.net':               'Entertainment',
  'gog galaxy':               'Entertainment',
  'itch':                     'Entertainment',
  'retroarch':                'Entertainment',
  'openemu':                  'Entertainment',
  'twitch':                   'Entertainment',
  'netflix':                  'Entertainment',
  'disney+':                  'Entertainment',
  'amazon prime video':       'Entertainment',
  'youtube music':            'Entertainment',
  'soundcloud':               'Entertainment',
  'deezer':                   'Entertainment',
  'tidal':                    'Entertainment',
  'garageband':               'Entertainment',
  'photo booth':              'Entertainment',
  'quicktime player':         'Entertainment',
  'chess':                    'Entertainment',
  'stardew valley':           'Entertainment',
  'minecraft':                'Entertainment',
  'league of legends':        'Entertainment',
  'twitterrific':             'Entertainment',
  'tweetbot':                 'Entertainment',
  'ivory':                    'Entertainment',
  'mango 5star':              'Entertainment',
  'news':                     'Entertainment',

  // ── Utilities ─────────────────────────────────────────────────────────────
  'finder':                   'Utilities',
  'system preferences':       'Utilities',
  'system settings':          'Utilities',
  'activity monitor':         'Utilities',
  'disk utility':             'Utilities',
  'console':                  'Utilities',
  'keychain access':          'Utilities',
  '1password':                'Utilities',
  '1password 7':              'Utilities',
  'bitwarden':                'Utilities',
  'keepassxc':                'Utilities',
  'dashlane':                 'Utilities',
  'lastpass':                 'Utilities',
  'alfred':                   'Utilities',
  'raycast':                  'Utilities',
  'launchbar':                'Utilities',
  'bartender':                'Utilities',
  'bartender 4':              'Utilities',
  'ice':                      'Utilities',
  'cleanmymac':               'Utilities',
  'cleanmymac x':             'Utilities',
  'daisydisk':                'Utilities',
  'istat menus':              'Utilities',
  'amphetamine':              'Utilities',
  'lungo':                    'Utilities',
  'caffeine':                 'Utilities',
  'rectangle':                'Utilities',
  'rectangle pro':            'Utilities',
  'magnet':                   'Utilities',
  'moom':                     'Utilities',
  'bettersnaptool':           'Utilities',
  'bettertouchtool':          'Utilities',
  'karabiner-elements':       'Utilities',
  'karabiner':                'Utilities',
  'keyboard maestro':         'Utilities',
  'automator':                'Utilities',
  'shortcuts':                'Utilities',
  'dropbox':                  'Utilities',
  'google drive':             'Utilities',
  'onedrive':                 'Utilities',
  'mega':                     'Utilities',
  'the unarchiver':           'Utilities',
  'archiver':                 'Utilities',
  'keka':                     'Utilities',
  'transmit':                 'Utilities',
  'transmit 5':               'Utilities',
  'cyberduck':                'Utilities',
  'filezilla':                'Utilities',
  'cleanshot x':              'Utilities',
  'shottr':                   'Utilities',
  'flameshot':                'Utilities',
  'preview':                  'Utilities',
  'maps':                     'Utilities',
  'weather':                  'Utilities',
  'stocks':                   'Utilities',
  'home':                     'Utilities',
  'reminders':                'Utilities',
  'calendar':                 'Utilities',
  'contacts':                 'Utilities',
  'photos':                   'Utilities',
  'image capture':            'Utilities',
  'calculator':               'Utilities',
  'font book':                'Utilities',
  'migration assistant':      'Utilities',
  'time machine':             'Utilities',
  'hazel':                    'Utilities',
  'setapp':                   'Utilities',
  'apple configurator':       'Utilities',
  'script editor':            'Work',
  'paint':                    'Utilities',
  'notepad':                  'Utilities',
  'snipping tool':            'Utilities',
  'task manager':             'Utilities',
  'control panel':            'Utilities',
  'microsoft store':          'Utilities',
  'windows explorer':         'Utilities',
};

/**
 * App names (lowercase) that should get keyword-based rules instead of a
 * single automatic rule, because context (URL / window title) determines
 * whether the session is work or entertainment.
 */
export const BROWSER_APPS = new Set([
  'chrome', 'google chrome',
  'safari',
  'firefox', 'firefox developer edition',
  'edge', 'msedge', 'microsoft edge',
  'brave browser', 'brave',
  'opera', 'opera gx',
  'arc',
  'vivaldi',
  'chromium',
  'waterfox',
  'librewolf',
  'tor browser',
]);

export const BROWSER_WORK_KEYWORDS = [
  'github', 'gitlab', 'bitbucket',
  'stackoverflow', 'stackoverflow.com',
  'docs', 'documentation', 'mdn',
  'localhost', '127.0.0.1',
  'jira', 'confluence', 'linear', 'notion',
  'figma', 'vercel', 'netlify',
  'aws', 'azure', 'gcp', 'console.cloud',
  'google docs', 'google sheets', 'google slides',
  'calendar.google',
];

export const BROWSER_ENTERTAINMENT_KEYWORDS = [
  'youtube', 'youtu.be',
  'netflix', 'hulu', 'disneyplus', 'disney+',
  'twitch', 'kick.com',
  'reddit',
  'twitter', 'x.com',
  'instagram', 'tiktok',
  'facebook', 'fb.com',
  '9gag', 'imgur',
  'bilibili',
];
